[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name         tail
    Path         /app/memory/system.log
    Parser       syslog-custom
    Tag          devagent.logs
    Refresh_Interval 2

[OUTPUT]
    Name            opensearch
    Match           *
    Host            opensearch
    Port            9200
    Index           devagent-logs
    Type            _doc
    HTTP_User       admin
    HTTP_Passwd     admin
    tls             Off
    tls.verify      Off
    Suppress_Type_Name On
